"""
@Author:xuyinglai
@Date:2026/7/21
@DESC:
"""
str1 = "Life's but a walking shadow, a poor player that struts and frets his hour upon the stage and then is heard no more. — Macbeth "
str2 = str1.lower()
print(str2)
a = str2.count('a')
print("[a]", a)
b = str2.count('b')
print("[b]", b)
c = str2.count('c')
print("[c]", c)

d = str2.count('d')
print("[d]", d)
e = str2.count('e')
print("[e]", e)
f = str2.count('f')
print("[f]", f)
g = str2.count('g')
print("[g]", g)
h = str2.count('h')
print("[h]", h)
i = str2.count('i')
print("[i]", i)
j = str2.count('j')
print("[j]", j)
k = str2.count('k')
print("[k]", k)
l = str2.count('l')
print("[l]", l)
m = str2.count('m')
print("[m]", m)
n = str2.count('n')
print("[n]", n)
o = str2.count('o')
print("[o]", o)
p = str2.count('p')
print("[p]", p)
q = str2.count('q')
print("[q]", q)
r = str2.count('r')
print("[r]", r)
s = str2.count('s')
print("[s]", s)
t = str2.count('t')
print("[t]", t)
u = str2.count('u')
print("[u]", u)
v = str2.count('v')
print("[v]", v)
w = str2.count('w')
print("[w]", w)
x = str2.count('x')
print("[x]", x)
y = str2.count('y')
print("[y]", y)
z = str2.count('z')
print("[z]", z)
print(max(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z))
